### PR TITLE
Add driver cameras

### PR DESCRIPTION
**Pull request by maxh65000**
We should test this before it's merged

### CODE REVIEW

**Comment by maxh65000** [comment]
I'm having issues with Shuffleboard crashing on my machine and I couldn't test this.

**Comment by joecaraccio** [comment]
@maxh65000  Do you think the issues are local to your machine or an issue with shuffleboard in general? I saw some people say on ChiefDelphi shuffleboard is flakey. would be a nightmare if our dashboard was crashing mid match

**Comment by maxh65000** [comment]
I think it's local to my machine

**Comment by averwhy** [comment]
@maxh65000 will we be able to test on Thursday?

**Comment by maxh65000** [comment]
I think so. I'll be there.

**Comment by maxh65000** [comment]
Works

**Review by averwhy — APPROVED** [review]
it work lets do

**Pull request merged**
