### PR TITLE
Camera tuning

### LINKED ISSUE #103: Develop a Image Capturing Solution for Camera Tuning
Daniel, Avery,

I have a really important task for you guys that we have been overlooking.  

A quick high level runthrough on what the vision code does now:
https://github.com/Team138Entropy/Entropy2020/blob/Production/EVHighGoal.py

This python script runs on a raspberry pi and takes constant frames off from the USB Camera (Ps3Eye). The camera's settings are very low brightness, as the design is to pickup only the reflective tape. Here is an example: https://imgur.com/jpBJGdr

From there, the python code does some HSV filtering to essentially try to filter out as much in the image that isn't that greenish target color as possible, to then get its center point in pixels, and translate the target to a rotation.

Here is the issue though! The lighting is going to be inconsistent, and we are going to need to tune our desired HSV ranges at different venues. HSV is just a color system, and the ranges say we will allow all colors within these numbers.

**What we need**
Is a way to capture many images of field from our camera. We can save these images to the Raspberry pi, and then in our team pit at competitions, go through them and determine the best HSV ranges to use based on the lighting of the venue. Some of these competitions are going to be in dimly lit gyms, some will be really bright and when we go to New Englands we will be in a legit arena.

To do this I need you guys to create a python script, that can run on our raspberry pi's and constantly take samples from the camera. We will load that script on during a practice match and take as many samples of how the target looks all over the field. Then we can take all the images off the raspberry pi and determine the best HSV ranges to use on our tracking scripts.

Make sense? I wanted to get these thoughts on paper before tonight.. really important we come up with a solid way to do this as the fate of our vision tracking is dependent upon it.

I think you guys are capable of putting together something awesome for this. If you need any help, talk to Me, Nick or Deep. All three of us know Python well.

### PR DESCRIPTION
**Pull request by averwhy**
This shouldn't be approved until we test it. I will be in on Saturday 2/15, but not Friday (today). For now, I'm just making this so we have it here and can attach it to the issue.

### CODE REVIEW

**Comment by joecaraccio** [comment]
Avery.. good work with this! only one thing to note that I didn't specify earlier,

we have two vision tracking systems.. 'EVBall' and 'EVHighGoal'. So we will need to create two versions of this file, one that runs on our ball camera (for intake lineup) and one for the goals. Goal one is much more important. The only thing that needs to change from the Goal one to the Ball one is the image size:

Goal Camera Image Size - 640x480
Ball Camera Image Size - 320x240

(we had to bump the goal camera's size up because it was difficult to see from so far away). The larger the resolution, the lower the camera's FPS... so lower the better

Just get everything working with the goal calibration file and then we can change the size easily.

**Comment by averwhy** [comment]
@joecaraccio Fair enough, it should be easy!

**Comment by maxh65000** [comment]
YSK that you can mark PRs when you create them as a draft and then later mark them as ready for approval. IDK if you can do that now, though.

**Comment by averwhy** [comment]
Almost done. I will finish it tonight (2/19/20). I just have to finish the folder stuff and make the 2nd file

**Comment by averwhy** [comment]
This should be ready, let me know when i can merge it into master. @joecaraccio @Nick-P-Orr

**Review by codemankey — APPROVED** [review]

**Comment by averwhy** [comment]
max is cringe he merged before I did >:(

Oh well glad we have these files in place

**Pull request merged**
