### PR TITLE
Comp auto

### PR DESCRIPTION
**Pull request by maxh65000**

### CODE REVIEW

**Comment by jhinspeter** [comment]
Same goes for "fix". Absolutely useless commit massage.

**Comment by maxh65000** [comment]
i was in a rush because nick l was angry

**Review by onedeadeye — APPROVED** [review]

**Comment by jhinspeter** [comment]
OK. Sorry for being short. Great work getting the Integration branch merged
and fixing my code review comments.

When everything's merged, let's tag the code. Something like
"Pre-Bridgewater Configuration"

**Comment by maxh65000** [comment]
sounds good

**Pull request merged**
