### PR TITLE
Merge Joe branch

### PR DESCRIPTION
**Pull request by maxh65000**

### CODE REVIEW

**Comment by maxh65000** [comment]
@joecaraccio you should know your code didn't build in ci

**Comment by maxh65000** [comment]
Setting your indentation to 2 spaces should reduce the merge conflicts when this is eventually merged.

**Comment by joecaraccio** [comment]
@maxh65000 if you want to merge this you probably could. All changes in RobotState.java should be overlapped with whats on the Joe Branch. Same with VisionManager.java.

The RobotState code isn't as mature as it needs to be right now but we will get it there

**Comment by maxh65000** [comment]
@joecaraccio could you have a look at the branch now? I've pulled in changes from master.

**Review by jhinspeter — APPROVED** [review]
Under protest (too many changes for a single pull request!!), approved.

**Pull request merged**
